# Generated by Django 4.1.4 on 2022-12-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
