# Generated by Django 4.1.4 on 2022-12-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="pets.tags"),
        ),
    ]
